export default {
  'code': 1,
  'desc': '查询成功111！',
  'recordCount': null,
  'currentPage': null,
  'data': {
    'openUserInfo': {
      'schoolCode': '201608001',
      'schoolName': '昭德英之泰学校',
      'userLoginName': 'instaiadmin',
      'userLoginTele': null,
      'userLoginEmail': null,
      'userActualName': '超级管理员',
      'userType': 1
    }
  },
  'list': [{
    'resId': 1000,
    'parentResId': -1,
    'resCode': '',
    'resName': '首页',
    'resUrl': '/',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0'
  },
  {
    'resId': 1111,
    'parentResId': -1,
    'resCode': '',
    'resName': 'demo',
    'resUrl': '',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': [
      {
        'resId': 11111,
        'parentResId': 1111,
        'resCode': '',
        'resName': '参考页面',
        'resUrl': '/demo/standard',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu',
        'childMenus': []
      }
    ]
  },
  {
    'resId': 8881,
    'parentResId': -1,
    'resCode': '',
    'resName': '信息管理',
    'resUrl': '',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': [{
      'resId': 88881,
      'parentResId': 8881,
      'resCode': '',
      'resName': '教职工信息管理',
      'resUrl': '/InfoManagement/StaffInfoManagement',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': [

      ]
    },
    {
      'resId': 88882,
      'parentResId': 8881,
      'resCode': '',
      'resName': '教职工资历管理',
      'resUrl': '/InfoManagement/StaffSeniManagement',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': []
    },
    {
      'resId': 88883,
      'parentResId': 8881,
      'resCode': '',
      'resName': '个人信息管理',
      'resUrl': '/InfoManagement/PerInfoManagement',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu'
    },
    {
      'resId': 888101,
      'parentResId': 8881,
      'resCode': '',
      'resName': '学生信息管理',
      'resUrl': '/InfoManagement/StuInforManage',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': [ ]
    }, {
      'resId': 8881014,
      'parentResId': 888101,
      'resCode': '',
      'resName': '学生个人信息管理',
      'resUrl': '/InfoManagement/StuPerInfor',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu'
    },
    {
      'resId': 88884,
      'parentResId': 8881,
      'resCode': '',
      'resName': '个人资历管理',
      'resUrl': '/InfoManagement/PerQualManagement',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu'
    },
    {
      'resId': 88885,
      'parentResId': 8881,
      'resCode': '',
      'resName': '教职工流失率',
      'resUrl': '/InfoManagement/StaffTurnRate',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu'
    },
    {
      'resId': 888100,
      'parentResId': 8881,
      'resCode': '',
      'resName': '教育局用户信息管理',
      'resUrl': '/InfoManagement/EduInfomation',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': []
    }
    ]
  },
  {
    'resId': 8882,
    'parentResId': 888,
    'resCode': '',
    'resName': '监督管理',
    'resUrl': '',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'isShort': true,
    'childMenus': [{
      'resId': 88821,
      'parentResId': 8882,
      'resCode': '',
      'resName': '教职工资历监督',
      'resUrl': '',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': [{
        'resId': 888211,
        'parentResId': 88821,
        'resCode': '',
        'resName': '资历查看',
        'resUrl': '/SuperviseManagement/AptitudeCheck',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu'
      },
      {
        'resId': 888212,
        'parentResId': 88821,
        'resCode': '',
        'resName': '反馈记录',
        'resUrl': '/SuperviseManagement/FeedbackRecord',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu'
      },
      {
        'resId': 888213,
        'parentResId': 88821,
        'resCode': '',
        'resName': '反馈管理',
        'resUrl': '/SuperviseManagement/FeedbackManagement',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu'
      }
      ]
    },
    {
      'resId': 88822,
      'parentResId': 8882,
      'resCode': '',
      'resName': '师资力量监督',
      'resUrl': '/SuperviseManagement/FacultySupervision',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': []
    },
    {
      'resId': 888233,
      'parentResId': 8882,
      'resCode': '',
      'resName': '教职工流失率监督',
      'resUrl': '/SuperviseManagement/StaffWastRateSupertwo',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu'
    },
    {
      'resId': 88824,
      'parentResId': 8882,
      'resCode': '',
      'resName': '督学反馈数量监督',
      'resUrl': '/SuperviseManagement/StudyFeedbackNumSuper',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu'
    },
    {
      'resId': 88825,
      'parentResId': 8882,
      'resCode': '',
      'resName': '幼儿园反馈数量监督',
      'resUrl': '/SuperviseManagement/KidsFeedbackNumSuper',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu'
    },
    {
      'resId': 88826,
      'parentResId': 8882,
      'resCode': '',
      'resName': '学生人数监控',
      'resUrl': '/SuperviseManagement/studentsNumSuper',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu'
    },
    {
      'resId': 88827,
      'parentResId': 8882,
      'resCode': '',
      'resName': '学生流动及流失率监控',
      'resUrl': '/SuperviseManagement/studentsChurnRateSuper',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu'
    }
    ]
  },
  {
    'resId': 8883,
    'parentResId': 888,
    'resCode': '',
    'resName': '系统管理',
    'resUrl': '',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': [{
      'resId': 88831,
      'parentResId': 8883,
      'resCode': '',
      'resName': '基本信息配置',
      'resUrl': '',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': [{
        'resId': 888311,
        'parentResId': 88831,
        'resCode': '',
        'resName': '系统岗位信息管理',
        'resUrl': '/SystemManagement/PostInfoManagement',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu'
      },
      {
        'resId': 888312,
        'parentResId': 88831,
        'resCode': '',
        'resName': '系统科目信息管理',
        'resUrl': '/SystemManagement/SubInfoManagement',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu'
      },
      {
        'resId': 888313,
        'parentResId': 88831,
        'resCode': '',
        'resName': '系统年级信息管理',
        'resUrl': '/SystemManagement/gradeInfoManagement',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu'
      },
      {
        'resId': 888314,
        'parentResId': 88831,
        'resCode': '',
        'resName': '幼儿园上报资料类型管理',
        'resUrl': '/SystemManagement/constitutionType',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu'
      },
      {
        'resId': 888315,
        'parentResId': 88831,
        'resCode': '',
        'resName': '教育局公告类型管理',
        'resUrl': '/SystemManagement/NoticeType',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu'
      },
      {
        'resId': 888316,
        'parentResId': 88831,
        'resCode': '',
        'resName': '系统职务信息管理',
        'resUrl': '/SystemManagement/informationManage',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu'
      }
      ]
    },
    {
      'resId': 88832,
      'parentResId': 8883,
      'resCode': '',
      'resName': '年级班级管理',
      'resUrl': '/SystemManagement/classAndGradManagement',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu'
    }
    ]
  },
  {
    'resId': 88887,
    'parentResId': 888,
    'resCode': '',
    'resName': '教务管理',
    'resUrl': '',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': [{
      'resId': 888871,
      'parentResId': 88887,
      'resCode': '',
      'resName': '年级班级主任管理',
      'resUrl': '/EducManagement/GradeClassTeaManagement',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': []
    },
    {
      'resId': 888872,
      'parentResId': 88887,
      'resCode': '',
      'resName': '任课教师管理',
      'resUrl': '/EducManagement/CourseTeachersManagement',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': []
    }
    ]
  }, {
    'resId': 88889,
    'parentResId': 888,
    'resCode': '',
    'resName': '异动管理',
    'resUrl': '',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': [{
      'resId': 888891,
      'parentResId': 88889,
      'resCode': '',
      'resName': '异动管理',
      'resUrl': '/TransManagement/transactionManagement',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': []
    },
    {
      'resId': 888892,
      'parentResId': 88889,
      'resCode': '',
      'resName': '异动数量统计',
      'resUrl': '/TransManagement/transactionCount',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': []
    },
    {
      'resId': 888893,
      'parentResId': 88889,
      'resCode': '',
      'resName': '异动明细信息',
      'resUrl': '/TransManagement/transactionDetail',
      'resType': 2,
      'orderId': 1,
      'moduleName': 'portal',
      'arg1': 0,
      'arg2': 'A0',
      'icon': 'el-icon-menu',
      'childMenus': []
    }
    ]
  }, {
    'resId': 88890,
    'parentResId': 888,
    'resCode': '',
    'resName': '问卷调查',
    'resUrl': '',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': [
      {
        'resId': 88891,
        'parentResId': 88890,
        'resCode': '',
        'resName': '问卷调查',
        'resUrl': '/EvaluateSystem/questionnaireSurvey',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu',
        'childMenus': []
      }, {
        'resId': 88896,
        'parentResId': 88890,
        'resCode': '',
        'resName': '人员分组',
        'resUrl': '/EvaluateSystem/groupPeople',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu',
        'childMenus': []
      }, {
        'resId': 88897,
        'parentResId': 88890,
        'resCode': '',
        'resName': '问卷统计',
        'resUrl': '/EvaluateSystem/questionnaireStatistical',
        'resType': 2,
        'orderId': 1,
        'moduleName': 'portal',
        'arg1': 0,
        'arg2': 'A0',
        'icon': 'el-icon-menu',
        'childMenus': []
      }
    ]
  },
  {
    'resId': 88898,
    'parentResId': 8888,
    'resCode': '',
    'resName': '日程与校历',
    'resUrl': '/Calendar/Schedule',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': []
  },
  {
    'resId': 888104,
    'parentResId': 8888,
    'resCode': '',
    'resName': '账户管理(区管理员)',
    'resUrl': '/AccountManagement/AMOne',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': []
  },
  {
    'resId': 888105,
    'parentResId': 8888,
    'resCode': '',
    'resName': '账户管理(幼儿园)',
    'resUrl': '/AccountManagement/AMTwo',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': []
  },
  {
    'resId': 888106,
    'parentResId': 8888,
    'resCode': '',
    'resName': '账户管理(教育局)',
    'resUrl': '/AccountManagement/AMThree',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': []
  },
  {
    'resId': 888107,
    'parentResId': 8888,
    'resCode': '',
    'resName': '打印二维码',
    'resUrl': '/AccountManagement/AQrcodePrint',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': []
  },
  {
    'resId': 888108,
    'parentResId': 8888,
    'resCode': '',
    'resName': '权限管理(管理员)',
    'resUrl': '/PrivilegeManagement/PMOne',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': []
  },
  {
    'resId': 888109,
    'parentResId': 8888,
    'resCode': '',
    'resName': '权限管理(幼儿园)',
    'resUrl': '/PrivilegeManagement/PMTwo',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': []
  },
  {
    'resId': 888110,
    'parentResId': 8888,
    'resCode': '',
    'resName': '权限管理(教育局)',
    'resUrl': '/PrivilegeManagement/PMThree',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': []
  },
  {
    'resId': 888111,
    'parentResId': 8888,
    'resCode': '',
    'resName': '公告管理',
    'resUrl': '/NoticeManagement/NManagement',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': []
  },
  {
    'resId': 888113,
    'parentResId': 8888,
    'resCode': '',
    'resName': '园资料审核',
    'resUrl': '/ConstitutionManagement/CMOne',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': []
  },
  {
    'resId': 888117,
    'parentResId': 8888,
    'resCode': '',
    'resName': '园资料上报',
    'resUrl': '/ConstitutionManagement/CMTwo',
    'resType': 2,
    'orderId': 1,
    'moduleName': 'portal',
    'arg1': 0,
    'arg2': 'A0',
    'icon': 'el-icon-menu',
    'childMenus': []
  }
  ]
}
